local_rank: 0

load_path: null # none
rng_seed: 0
mode: 
  train: True
  inference: False # or inference

logname: null # none
expname: null
expid: null
seed: 4165
wandb:
  use_wandb: True
  project: moviecuts  # name of the wandb project
  entity: pardoalejo