local_rank: 0

load_path: null # none
rng_seed: 0
mode: train # or test

logname: null # none
expname: null
expid: null

wandb:
  use_wandb: False
  project: moviecuts  # name of the wandb project
  entity: null